create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ar text not null,
  slug text not null unique,
  icon text not null default '',
  sort_order integer not null default 0
);

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ar text not null,
  logo_url text
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ar text not null,
  description_en text not null default '',
  description_ar text not null default '',
  price_bhd numeric(10, 3) not null,
  old_price_bhd numeric(10, 3),
  brand_id bigint references public.brands(id),
  category_id bigint references public.categories(id),
  condition text not null default 'New',
  warranty text not null default '1 year',
  installments text not null default 'Available',
  badge text not null default 'none',
  stock_status text not null default 'In stock',
  is_active boolean not null default true,
  storage text[] not null default '{}',
  colors text[] not null default '{}',
  specifications_en text[] not null default '{}',
  specifications_ar text[] not null default '{}',
  likes integer not null default 0,
  sold_count integer not null default 0,
  rating numeric(2, 1) not null default 0,
  review_count integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  sort_order integer not null default 0
);

create table if not exists public.settings (
  id bigint primary key default 1,
  store_whatsapp_number text not null,
  store_phone_sales text not null,
  store_phone_repairs text not null,
  maps_url text not null,
  store_name_en text not null,
  store_name_ar text not null,
  promo_text_en text not null default '',
  promo_text_ar text not null default '',
  constraint single_settings_row check (id = 1)
);

alter table public.categories enable row level security;
alter table public.brands enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.settings enable row level security;

create policy "Public can read categories" on public.categories for select using (true);
create policy "Public can read brands" on public.brands for select using (true);
create policy "Public can read active products" on public.products for select using (is_active = true);
create policy "Public can read product images" on public.product_images for select using (true);
create policy "Public can read settings" on public.settings for select using (true);

create policy "Admins can manage categories" on public.categories for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage brands" on public.brands for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage products" on public.products for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage product images" on public.product_images for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage settings" on public.settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
