create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ar text not null,
  slug text not null unique,
  icon text not null default '',
  sort_order integer not null default 0
);

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ar text not null,
  logo_url text,
  sort_order integer not null default 0
);

alter table public.brands
add column if not exists sort_order integer not null default 0;

alter table public.brands add column if not exists homepage_url text;
alter table public.brands add column if not exists is_visible boolean not null default true;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ar text not null,
  description_en text not null default '',
  description_ar text not null default '',
  price_bhd numeric(10, 3) not null,
  old_price_bhd numeric(10, 3),
  brand_id bigint references public.brands(id),
  category_id bigint references public.categories(id),
  condition text not null default 'New',
  warranty text not null default '1 year',
  installments text not null default 'Available',
  badge text not null default 'none',
  stock_status text not null default 'In stock',
  is_active boolean not null default true,
  storage text[] not null default '{}',
  colors text[] not null default '{}',
  specifications_en text[] not null default '{}',
  specifications_ar text[] not null default '{}',
  likes integer not null default 0,
  sold_count integer not null default 0,
  rating numeric(2, 1) not null default 0,
  review_count integer not null default 0,
  created_at timestamptz not null default now()
);

alter table public.products
add column if not exists brand text,
add column if not exists category text,
add column if not exists specs_en text[] not null default '{}',
add column if not exists specs_ar text[] not null default '{}',
add column if not exists accessories jsonb not null default '[]',
add column if not exists price numeric(10, 3),
add column if not exists old_price numeric(10, 3),
add column if not exists image_url text,
add column if not exists image_urls text[] not null default '{}',
add column if not exists status text,
add column if not exists is_featured boolean not null default false,
add column if not exists is_new boolean not null default false,
add column if not exists is_offer boolean not null default false,
add column if not exists views integer not null default 0,
add column if not exists whatsapp_clicks integer not null default 0,
add column if not exists sort_order integer not null default 0,
add column if not exists data jsonb not null default '{}';

create table if not exists public.product_variants (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  color_name text,
  color_code text,
  storage text,
  ram text,
  price_bhd numeric(10, 3),
  stock_status text not null default 'available',
  image_gallery jsonb not null default '[]',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.product_images (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  url text not null,
  color text,
  sort_order integer not null default 0
);

alter table public.product_images
add column if not exists color text;

create table if not exists public.homepage_sections (
  id text primary key,
  section_type text not null default 'custom',
  title_en text not null default '',
  title_ar text not null default '',
  content jsonb not null default '{}'::jsonb,
  source text not null default '',
  is_visible boolean not null default true,
  sort_order integer not null default 0,
  publication_state text not null default 'published' check (publication_state in ('draft', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.store_settings (
  id text primary key default 'main',
  logo_url text,
  banner_url text,
  whatsapp text,
  phone_sales text,
  phone_repairs text,
  maps_url text,
  instagram text,
  site_url text,
  benefit_pay_enabled boolean not null default false,
  benefit_pay_qr text,
  benefit_pay_account_holder text,
  benefit_pay_phone text,
  iban text,
  benefit_pay_instructions_ar text,
  benefit_pay_instructions_en text,
  payment_options text,
  delivery_options text,
  whatsapp_template text,
  updated_at timestamptz not null default now()
);

alter table public.store_settings
add column if not exists benefit_pay_enabled boolean not null default false,
add column if not exists benefit_pay_account_holder text,
add column if not exists benefit_pay_phone text,
add column if not exists benefit_pay_instructions_ar text,
add column if not exists benefit_pay_instructions_en text;

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  product_id bigint references public.products(id) on delete set null,
  action text not null,
  customer_name text,
  customer_phone text,
  metadata jsonb not null default '{}',
  created_at timestamptz not null default now()
);

create table if not exists public.employee_roles (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null unique,
  role text not null default 'staff',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.settings (
  id bigint primary key default 1,
  store_whatsapp_number text not null,
  store_phone_sales text not null,
  store_phone_repairs text not null,
  maps_url text not null,
  store_name_en text not null,
  store_name_ar text not null,
  promo_text_en text not null default '',
  promo_text_ar text not null default '',
  constraint single_settings_row check (id = 1)
);

alter table public.categories enable row level security;
alter table public.brands enable row level security;
alter table public.products enable row level security;
alter table public.product_images enable row level security;
alter table public.product_variants enable row level security;
alter table public.homepage_sections enable row level security;
alter table public.store_settings enable row level security;
alter table public.leads enable row level security;
alter table public.employee_roles enable row level security;
alter table public.settings enable row level security;

create policy "Public can read categories" on public.categories for select using (true);
create policy "Public can read brands" on public.brands for select using (true);
create policy "Public can read active products" on public.products for select using (is_active = true);
create policy "Public can read product images" on public.product_images for select using (true);
create policy "Public can read product variants" on public.product_variants for select using (true);
create policy "Public can read published homepage sections" on public.homepage_sections for select using (publication_state = 'published' and is_visible = true);
create policy "Public can read store settings" on public.store_settings for select using (true);
create policy "Public can read settings" on public.settings for select using (true);

create policy "Admins can manage categories" on public.categories for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage brands" on public.brands for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage products" on public.products for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage product images" on public.product_images for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage product variants" on public.product_variants for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage homepage sections" on public.homepage_sections for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage store settings" on public.store_settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage leads" on public.leads for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage employee roles" on public.employee_roles for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
create policy "Admins can manage settings" on public.settings for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
values ('site-assets', 'site-assets', true)
on conflict (id) do update set public = true;
